### ISSUE TITLE
Provide instalation instructions for platform

### ISSUE THREAD

**Issue by ahojsenn** [pixelated-project/pixelated-platform#16]
Could you provide something for me to learn how to install ist (preferrably on my rpi ;-)).
Johannes

**Comment by varac** [comment]
Hi Johannes, 
sorry for responding so late but your issue was overseen. 
We'll prioritize the pixelated install howto and will come up with something soon.

Basically, the pixelated platform is just based on a leap email provider installation.
If you want to provide  webmail  and the pixelated-dispatcher installed together on one machine.

If you want an "organisational setup" (as we call it),  meaning that ppl access their encrypted mails using a central webmail server, you would install the pixelated-dispatcher packages on top of it.

For the "activist setup" you would install the pixelated-useragent locally on your laptop to access your mail.

if you have any further questions, you can get in contact by mail or irc too, see https://pixelated-project.org/ for details.

**Comment by lqust** [comment]
This will be handled in https://github.com/pixelated-project/pixelated-platform/issues/65
